package com.example.liberex.xdo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2015-04-09T15:26:40.789-04:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "AdminServiceService", 
                  wsdlLocation = "file:/Users/calin/git/liberex/liberex/src/main/resources/schemas/WS_AdminService.wsdl",
                  targetNamespace = "urn:example.com:liberex:v1") 
public class AdminServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:example.com:liberex:v1", "AdminServiceService");
    public final static QName AdminServiceSoap11 = new QName("urn:example.com:liberex:v1", "AdminServiceSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/calin/git/liberex/liberex/src/main/resources/schemas/WS_AdminService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AdminServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/calin/git/liberex/liberex/src/main/resources/schemas/WS_AdminService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AdminServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AdminServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdminServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AdminServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AdminServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AdminServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AdminService
     */
    @WebEndpoint(name = "AdminServiceSoap11")
    public AdminService getAdminServiceSoap11() {
        return super.getPort(AdminServiceSoap11, AdminService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdminService
     */
    @WebEndpoint(name = "AdminServiceSoap11")
    public AdminService getAdminServiceSoap11(WebServiceFeature... features) {
        return super.getPort(AdminServiceSoap11, AdminService.class, features);
    }

}
