package com.example.liberex.xdo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2015-04-09T15:26:40.748-04:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "urn:example.com:liberex:v1", name = "AdminService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AdminService {

    @WebMethod(operationName = "GetSystemStatus", action = "urn:example.com:liberex:v1/GetSystemStatus")
    @WebResult(name = "GetSystemStatusResponse", targetNamespace = "urn:example.com:liberex:v1", partName = "GetSystemStatusResponse")
    public GetSystemStatusResponse getSystemStatus(
        @WebParam(partName = "GetSystemStatusRequest", name = "GetSystemStatusRequest", targetNamespace = "urn:example.com:liberex:v1")
        GetSystemStatusRequest getSystemStatusRequest
    );

    @WebMethod(operationName = "ExecuteProgram", action = "urn:example.com:liberex:v1/ExecuteProgram")
    @WebResult(name = "ExecuteProgramResponse", targetNamespace = "urn:example.com:liberex:v1", partName = "ExecuteProgramResponse")
    public ExecuteProgramResponse executeProgram(
        @WebParam(partName = "ExecuteProgramRequest", name = "ExecuteProgramRequest", targetNamespace = "urn:example.com:liberex:v1")
        ExecuteProgramRequest executeProgramRequest
    );
}
